version: '3.9'

services: 

  society-sorcerer-dev:
    user: 185:33
    image: 'docker.benevolo.de/stiehl-seine-perlen/society-sorcerer:dev'
    restart: unless-stopped
    environment:
      QUARKUS_HTTP_PORT: 8082
      QUARKUS_DATASOURCE_DB_KIND: POSTGRESQL
      QUARKUS_DATASOURCE_USERNAME: society-sorcerer
      QUARKUS_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-dev:5432/finance
      QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION: drop-and-create 
      QUARKUS_HTTP_CORS_ORIGINS: "https://dev.benevolo.de" ## allow frontend as origin
    
    networks:
      - society-sorcerer
      - kafka

  postgres-dev:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: society-sorcerer
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - /microservices/society-sorcerer/postgres/data/:/var/lib/postgresql/data/
    networks:
      - society-sorcerer
      
networks:
  kafka:
   external: true
  society-sorcerer:
   external: true