-- INSERT INTO Address VALUES (1, 'Ingolstadt', 'GERMANY', '10', '85049', 'Esplanade');
--
-- INSERT INTO Association VALUES (1, 'Neuland e.V.', 'info@neuland.de', 'Verein für Informatikinteressierte', 1);